version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/maxgui"
    schedule:
      interval: "monthly"
    versioning-strategy: lockfile-only

  - package-ecosystem: "npm"
    directory: "/maxgui/queryEditor/package"
    schedule:
      interval: "monthly"
    # ignore any version updates that affect the manifest
    versioning-strategy: lockfile-only