version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/maxgui"
    schedule:
      interval: "monthly"
    versioning-strategy: lockfile-only
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/maxgui/workspace/package"
    schedule:
      interval: "monthly"
    # ignore any version updates that affect the manifest
    versioning-strategy: lockfile-only
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]